import { GoogleGenAI } from "@google/genai";
import { ComplianceRecord, ComplianceStatus } from "./types";

// The API key MUST be obtained exclusively from the environment variable process.env.API_KEY.
const apiKey = process.env.API_KEY;

/**
 * Generates compliance risk insights using Gemini 3 Flash.
 * @param compliances List of compliance records to analyze.
 */
export const getComplianceInsights = async (compliances: ComplianceRecord[]) => {
  // Graceful fallback if API key is not yet set up
  if (!apiKey) {
    console.warn("Gemini API Key missing. Insights will be disabled.");
    return ["AI Insights are currently unavailable: API Key not configured in environment."];
  }

  // Initialize client only when needed to ensure up-to-date environment access
  const ai = new GoogleGenAI({ apiKey });

  const pending = compliances.filter(c => c.status !== ComplianceStatus.COMPLETED);
  const dataSummary = pending.map(p => ({
    name: p.name,
    due: p.dueDate,
    status: p.status,
    reason: p.delayReason || "Not provided"
  }));

  const prompt = `As a financial compliance risk analyst, review the following pending tax compliances and provide a high-level executive summary (3-4 bullet points) on potential risks, penalties, and prioritized action items.
  
  Data: ${JSON.stringify(dataSummary)}
  
  Format: Return a JSON object with a key "summary" which is an array of strings.`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json"
      }
    });

    const text = response.text;
    if (!text) return ["No insights generated by the model."];
    
    const result = JSON.parse(text);
    return result.summary || ["No specific risks identified at this time."];
  } catch (error) {
    console.error("AI Insight Error:", error);
    return ["The system was unable to generate AI insights due to an API or network error."];
  }
};